'use client';

import {
  addDoc,
  collection,
  doc,
  updateDoc,
  type Firestore,
} from 'firebase/firestore';
import { errorEmitter } from '../error-emitter';
import { FirestorePermissionError } from '../errors';
import type { PropostaStatus, Proposta } from '@/lib/types';

// Omit 'id' as it's auto-generated by Firestore.
type NewProposta = Omit<Proposta, 'id'>;

export async function addProposta(firestore: Firestore, proposta: NewProposta) {
  const propostasCollection = collection(firestore, 'propostas');
  
  return addDoc(propostasCollection, proposta).catch((serverError) => {
    const permissionError = new FirestorePermissionError({
      path: propostasCollection.path,
      operation: 'create',
      requestResourceData: proposta,
    });
    errorEmitter.emit('permission-error', permissionError);
    throw serverError;
  });
}

export async function updatePropostaStatus(firestore: Firestore, propostaId: string, status: PropostaStatus) {
    const propostaRef = doc(firestore, 'propostas', propostaId);

    return updateDoc(propostaRef, { status }).catch((serverError) => {
        const permissionError = new FirestorePermissionError({
            path: propostaRef.path,
            operation: 'update',
            requestResourceData: { status },
        });
        errorEmitter.emit('permission-error', permissionError);
        throw serverError;
    });
}

    